```{r setup}
#| message: false
#| include: false
library(tidyverse)
library(knitr)
library(googlesheets4)
```

# Dummy observations {.unnumbered}

Code example for data exploration.

```{r data}
#| message: false
#| warning: false
metadata <- read_sheet("https://docs.google.com/spreadsheets/d/1fq2owxMBLBwwibcdw2uQQFxnIhsMbaH4Qcj_xUwVvSQ/edit?gid=0#gid=0", col_types = "c") %>%  #nolint
  rename_all(tolower) %>%
  select(site, plot, treatment, year_of_harvest) %>%
  mutate(year_of_harvest = as.numeric(year_of_harvest)) %>%
  rename(harvest_year = year_of_harvest) %>%
  mutate(treatment = ifelse(treatment %in% c("Control", "Natural_Forest"),
                            "control", "logged"))
data <- read_csv("data/raw_data/aggregated_data.csv") %>%
  rename_all(tolower) %>%
  left_join(read_tsv("data/raw_data/environment.tsv") %>%
              gather(env, env_value, -site, -plot)) %>%
  left_join(metadata)
```

```{r fig1}
#| fig-cap: "Dummy figure 1 - traj."
data %>%
  ggplot(aes(year, value, group = paste(site, plot))) +
  geom_line() +
  theme_bw() +
  facet_wrap(~variable, scales = "free_y") +
  theme(
    axis.title = element_blank(),
    strip.text = element_text(size = 6)
  )
```

```{r fig2}
#| fig-cap: "Dummy figure 2 - env."
data %>%
  filter(variable == "agb", env == "cwd") %>%
  na.omit() %>%
  ggplot(aes(year, value, group = paste(site, plot), col = env_value)) +
  geom_line() +
  theme_bw() +
  scale_color_viridis_c("Climate\nwater\ndeficit\n[ mm ]") +
  xlab("") +
  ylab(expression("AGB [" ~ Mg ~ ha^{
    -1
  } ~ "]"))
```

```{r fig3}
#| warning: false
#| fig-cap: "Dummy figure 3 - treatment."
data %>%
  filter(variable == "agb") %>%
  ggplot(aes(year, value, group = paste(site, plot), col = treatment)) +
  geom_line() +
  theme_bw() +
  xlab("") +
  ylab(expression("AGB [" ~ Mg ~ ha^{
    -1
  } ~ "]")) +
  facet_wrap(~ site) +
  geom_vline(aes(xintercept = harvest_year)) +
  theme(legend.position = "bottom")
```
