```{r set}
#| message: false
#| include: false
library(tidyverse)
library(knitr)
library(cmdstanr)
library(brms)
```

# Controls

```{r}
lab <- expression("BA [" ~ m^2 ~ m^{
  -2
} ~ "]")
mdata <- bind_rows(
  read_tsv("data/derived_data/data_pre.tsv", col_types = cols()),
  read_tsv("data/derived_data/data_old.tsv", col_types = cols())
) %>%
  filter(variable == "ba") %>% 
  mutate(sitenum = as.numeric(as.factor(site))) %>% 
  mutate(plotnum = as.numeric(as.factor(paste(site, plot))))
mdata %>% 
  ggplot(aes(y, fill = plot)) +
  geom_histogram() +
  theme_bw() +
  facet_wrap(~ site, scales = "free_y") +
  scale_fill_discrete(guide = "none") +
  xlab(lab) + ylab("")
```

```{r}
model_path <- file.path("models", paste0("control", ".stan"))
stan_model <- cmdstan_model(model_path)
fit <- stan_model$sample(
    data = list(
      n_obs = nrow(mdata),
      n_site = max(mdata$sitenum),
      n_plot = max(mdata$plotnum),
      y = mdata$y,
      site = mdata$sitenum,
      plot = mdata$plotnum
    ),
    chains = 4,
    parallel_chains = 4,
    save_warmup = FALSE,
    refresh = 100
)
fit$draws("mu") %>% mcmc_dens()
```

```{r}
index <- mdata %>% 
  select(sitenum, site) %>% 
  unique()
fit$summary("mu") %>% 
  separate(variable, c("mu", "sitenum"), convert = TRUE) %>% 
  left_join(index) %>% 
  ggplot(aes(median, site)) +
  geom_segment(aes(x = median - sd, xend = median + sd)) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  theme_bw() +
  xlab(lab) + ylab("")
```

```{r}
data_rec <- read_tsv("data/derived_data/data_rec.tsv", col_types = cols()) %>%
  filter(variable == "ba") %>% 
  select(-sitenum) %>% 
  left_join(index)
model_path <- file.path("models", paste0("stp3", ".stan"))
stan_model <- cmdstan_model(model_path)
ind_rec <- data_rec %>%
    select(site, plot, sitenum, plotnum_rec) %>%
    unique() %>%
    arrange(plotnum_rec)
fit2 <- stan_model$sample(
    data = list(
      n = nrow(data_rec),
      s = max(data_rec$sitenum),
      p = max(data_rec$plotnum_rec),
      y = data_rec$y,
      t = data_rec$rel_year - 3,
      site = data_rec$sitenum,
      plot = data_rec$plotnum_rec,
      site_plot = ind_rec$sitenum,
      mu_theta_s = fit$summary("mu")$median,
      sigma_theta_s = fit$summary("mu")$sd
    ),
    chains = 4,
    parallel_chains = 4,
    save_warmup = FALSE,
    refresh = 100
)
```

```{r fit}
fit2
```

```{r pvo}
data_rec$preds <- fit2$summary(c("mu"), median)$median
rmse_rec <- sqrt(mean((data_rec$preds - data_rec$y)^2, na.rm = TRUE))
data_rec %>%
  ggplot(aes(preds, y)) +
  geom_point(alpha = 0.25) +
  geom_abline(col = "red", linetype = "dashed") +
  ggtitle("Recovery", paste("RMSE =", round(rmse_rec, 2))) +
  theme_bw() +
  xlab("Predicted") +
  ylab("Observed")
```

```{r proj}
data_pre <- read_tsv("data/derived_data/data_pre.tsv", col_types = cols()) %>%
    filter(variable == "ba")
  data_old <- read_tsv("data/derived_data/data_old.tsv", col_types = cols()) %>%
    filter(variable == "ba")
fit2$summary("y_pred", "median") %>%
    separate(variable,
      c("y", "pred", "rel_year", "plotnum_rec"),
      convert = TRUE
    ) %>%
    select(-y, -pred) %>%
    rename(y = median) %>%
    mutate(rel_year = rel_year + 3) %>%
    left_join(data_rec %>%
                select(site, plot, plotnum_rec) %>%
                unique()) %>%
    ggplot(aes(rel_year, y)) +
    geom_boxplot(
      data = data_old %>% mutate(rel_year = 61),
      width = 4, fill = NA
    ) +
    geom_boxplot(
      data = data_pre %>% mutate(rel_year = -1),
      width = 4, fill = NA
    ) +
    geom_point(aes(group = paste(site, plot), col = plot),
      data = data_rec, alpha = .5
    ) +
    geom_line(aes(group = paste(site, plot), col = plot)) +
    facet_wrap(~site, scales = "free") +
    theme_bw() +
    xlab("") +
    theme(legend.position = "bottom") +
    ylab(lab) +
    scale_color_discrete(guide = "none")
```

```{r}
index <- mdata %>% 
  select(sitenum, site) %>% 
  unique()
bind_rows(
  fit2$summary("theta_s") %>% 
  separate(variable, c("mu", "s", "sitenum"), convert = TRUE) %>% 
  left_join(index) %>%
  select(site, mu, median, sd, q5, q95) %>% 
  mutate(type = "posterior"),
  fit$summary("mu") %>% 
  separate(variable, c("mu", "sitenum"), convert = TRUE) %>% 
  left_join(index) %>%
  select(site, mu, median, sd, q5, q95) %>% 
  mutate(type = "prior")
) %>% 
  ggplot(aes(median, site, col = type)) +
  geom_segment(aes(x = median - sd, xend = median + sd)) +
  geom_segment(aes(x = q5, xend = q95), size = .1) +
  geom_point() +
  theme_bw() +
  xlab(lab) + ylab("")
```
