```{r set}
#| message: false
#| include: false
library(tidyverse)
library(knitr)
library(cmdstanr)
library(bayesplot)
library(patchwork)
list.files("r", full.names = TRUE, pattern = ".R") %>%
  lapply(source)
```

# Str - AGB {.unnumbered}

Aboveground biomass recovery in tons per hectare derived from censuses using species names to derive first wood density and the biomass with the R package BIOMASS [@réjou-méchain2017].

```{r data}
#| message: false
#| warning: false
var <- "agb"
lab <- expression("AGB [ t" ~ ha^{
  -1
} ~ "]")
data <- load_all(var, lab)
```

## OGF

```{r ogf_data}
#| message: false
#| warning: false
#| fig-cap: "Old growth forests data."
ogf_data_fig(data)
```

```{r theta_ogf}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from old growth forests."
ogf_theta_fig(data)
```

```{r}
t <- data$data_ogf %>% 
  group_by(site, sitenum) %>% 
  summarise(median = median(value),
            sd = sd(value), 
            q5 = quantile(value, .0),
            q95 = quantile(value, 1)) %>% 
  mutate(type = "data")
data$fit_ogf$summary("mu") %>%
    separate(variable, c("mu", "sitenum"), convert = TRUE) %>%
    left_join(data$ind_ogf) %>% 
  mutate(type = "posterior") %>% 
  bind_rows(t) %>% 
    ggplot(aes(median, paste(site, type), col = type)) +
    geom_segment(aes(x = median - sd, xend = median + sd)) +
    geom_segment(aes(x = q5, xend = q95), size = .5) +
    geom_point() +
    theme_bw() +
    xlab(data$lab) +
    ylab(expression(theta[OGF]))

```

## STP

```{r load_stp}
#| message: false
#| warning: false
data$fit_stp
```

```{r pvo_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted versus observed."
pvo_fig(data)
```

```{r preds_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted trajectories."
proj_fig(data)
```

```{r theta_stp}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from recovery trajectories against its posterior."
rec_theta_fig(data)
```
