```{r set}
#| message: false
#| include: false
library(tidyverse)
library(knitr)
library(cmdstanr)
library(bayesplot)
library(loo)
library(patchwork)
list.files("r", full.names = TRUE, pattern = ".R") %>%
  lapply(source)
```

# Str - Gini {.unnumbered}

The Gini coefficient measures the inequality among the values of a the diameter distribution in censuses. A Gini coefficient of 0 reflects perfect equality, where all diameter values are the same, while a Gini coefficient of 1 (or 100%) reflects maximal inequality among diameters. See <https://en.wikipedia.org/wiki/Gini_coefficient>.

```{r data}
#| message: false
#| warning: false
var <- "gini"
lab <- "Gini index"
data <- load_all(var, lab)
```

## OGF

```{r ogf_data}
#| message: false
#| warning: false
#| fig-cap: "Old growth forests data."
ogf_data_fig(data)
```

```{r theta_ogf}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from old growth forests."
ogf_theta_fig(data)
```

## STP

```{r load_stp}
#| message: false
#| warning: false
data$fit_stp
```

```{r pvo_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted versus observed."
pvo_fig(data)
```

```{r preds_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted trajectories."
proj_fig(data)
```

```{r theta_stp}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from recovery trajectories against its posterior."
rec_theta_fig(data)
```
