```{r set}
#| message: false
#| include: false
library(tidyverse)
library(knitr)
library(cmdstanr)
library(bayesplot)
library(loo)
library(patchwork)
list.files("r", full.names = TRUE, pattern = ".R") %>%
  lapply(source)
```

# Div - FDiv {.unnumbered}

Functional diversity is measured through functional divergence Fdiv, the "Species deviance from the mean distance to the centre of gravity weighted by relative abundance" [@mouchet2010].

```{r data}
#| message: false
#| warning: false
var <- "FDiv"
lab <- expression("FDiv")
data <- load_all(var, lab)
```

## OGF

```{r ogf_data}
#| message: false
#| warning: false
#| fig-cap: "Old growth forests data."
ogf_data_fig(data)
```

```{r theta_ogf}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from old growth forests."
ogf_theta_fig(data)
```

## STP

```{r load_stp}
#| message: false
#| warning: false
data$fit_stp
```

```{r pvo_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted versus observed."
pvo_fig(data)
```

```{r preds_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted trajectories."
proj_fig(data)
```

```{r theta_stp}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from recovery trajectories against its posterior."
rec_theta_fig(data)
```

