```{r set}
#| message: false
#| include: false
library(tidyverse)
library(knitr)
library(cmdstanr)
library(bayesplot)
library(loo)
library(patchwork)
list.files("r", full.names = TRUE, pattern = ".R") %>%
  lapply(source)
```

# Func - SLA {.unnumbered}

Specific Leaf Area trajectories have been quantified using the community weighted mean, the average of the local distribution of a trait in a community. The trait value is weighted by tree basal area to better represent their biomass contribution in the community.

```{r data}
#| message: false
#| warning: false
var <- "SLA_cwm_ba"
lab <- expression("SLA [" ~ mm^2 ~ mg^{
  -1
} ~ "]")
data <- load_all(var, lab)
```

```{r theta_equ}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from forests at equilibirum."
equ_theta_fig(data)
```

```{r fit_rec}
#| message: false
#| warning: false
data$fit_rec
```

```{r pvo_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted versus observed."
pvo_fig(data)
```

```{r preds_stp}
#| message: false
#| warning: false
#| fig-cap: "Predicted trajectories."
#| fig-width: 10
#| fig-height: 10
proj_fig(data)
```

```{r theta_stp}
#| message: false
#| warning: false
#| fig-cap: "Theta posterior from recovery trajectories against its posterior."
rec_theta_fig(data)
```
