project:
  type: book
  output-dir: docs

book:
  title: "modelling"
  date: last-modified
  chapters:
    - index.qmd
    - 11_observations.qmd
    - 21_models.qmd
    - 31_stem.qmd
    - 32_wd.qmd
    - 33_agb.qmd
    - 34_fdiv.qmd
    - 35_div_q1_gen.qmd
    - 36_agb_mort.qmd
  appendices:
    - 91_stp_negative.qmd
    - 99_references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-fold: true
    number-depth: -1

editor: visual
